name: build-app
on:
  push:
  workflow_dispatch:
    inputs:
      disable_sccache:
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      disable_sccache:
        required: false
        type: boolean
jobs:
  build:
    runs-on: macos-14
    env:
      TES3MP_MAC_DISABLE_SANDBOX: 1
    steps:
      - name: Run sccache-cache unless disabled
        if: inputs.disable_sccache != true
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Configure sccache
        if: inputs.disable_sccache != true
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "TES3MP_MAC_USE_SCCACHE=1" >> $GITHUB_ENV
      - name: Select Xcode 15
        run: sudo xcode-select -s '/Applications/Xcode_15.0.1.app/Contents/Developer'
      - uses: actions/checkout@v4
      - run: brew install coreutils create-dmg gnu-sed meson nasm ninja patchutils python-setuptools
      - name: Build
        run: ./build.sh
      - name: Save .dmg as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: "*.dmg"
